### ISSUE TITLE
Gobabis Coordinates error on certificate

### ISSUE THREAD

**Issue by christophine** [cb-flts/stdm#64]
The coordinates on the certificates printed does not match with the coordinates of the Sunshine scheme that have been lodged with its respective coordinates in the WKT file.

The CRS that was used for Gobabis is 22/19. I attached the WKT file an the certificate that was printed with the  wrong coordinates.

[WKT_Pt153_PolygonFile_20200730_ORIGINAL.txt](https://github.com/cb-flts/flts/files/5464174/WKT_Pt153_PolygonFile_20200730_ORIGINAL.txt)
[3.pdf](https://github.com/cb-flts/flts/files/5464176/3.pdf)

**Comment by jkariukidev** [comment]
> 
> 
> The coordinates on the certificates printed does not match with the coordinates of the Sunshine scheme that have been lodged with its respective coordinates in the WKT file.
> 
> The CRS that was used for Gobabis is 22/19. I attached the WKT file an the certificate that was printed with the wrong coordinates.
> 
> [WKT_Pt153_PolygonFile_20200730_ORIGINAL.txt](https://github.com/cb-flts/flts/files/5464174/WKT_Pt153_PolygonFile_20200730_ORIGINAL.txt)
> [3.pdf](https://github.com/cb-flts/flts/files/5464176/3.pdf)

The plot annotation file that computes the destination CRS is responsible for this and it shall be re-configured to accomodate the new scheme plots.

**Comment by jkariukidev** [comment]
@christophine Perform a git pull and test whether the issue has been fixed.

**Comment by christophine** [comment]
@joseph Alright I will do that on Monday because I am currently not in whk.

**Comment by jkariukidev** [comment]
Thanks for closing the isuue.
