### ISSUE TITLE
Different font size on map figure

### ISSUE THREAD

**Issue by christophine** [cb-flts/stdm#65]
Hi Joseph could you kindly assist with the following issue, I attached the final certificate that was generated. It seems to have bigger fonts on the coordinates figure.

I did the latest git pull and updated the CB-FLTS.

Regards

**Comment by christophine** [comment]
![IMG_2463](https://user-images.githubusercontent.com/52163423/98539038-587ca500-2294-11eb-9513-e644865230e1.jpg)
![IMG_2462](https://user-images.githubusercontent.com/52163423/98539047-5c102c00-2294-11eb-9ebe-50c5af24cced.jpg)


Kindly see pictures of the issue I am talking about

**Comment by jkariukidev** [comment]
Having a look at it.

**Comment by christophine** [comment]
Sure. Thank you.

**Comment by jkariukidev** [comment]
The issue has been fixed in the most recent commits. Kindly perform a git pull and confirm that you have the following layouts in your certificate so that we can close this issue. 
![fixed_annotation](https://user-images.githubusercontent.com/23359514/98547069-abf8ee00-22a8-11eb-8597-9a3502a4da6a.png)
![fixed_annotation_1](https://user-images.githubusercontent.com/23359514/98547077-adc2b180-22a8-11eb-9c86-b4dd1b997b3d.png)
![fixed_label](https://user-images.githubusercontent.com/23359514/98547083-aef3de80-22a8-11eb-9e36-c9bbcda6f13b.png)
![fixed_label_1](https://user-images.githubusercontent.com/23359514/98547088-b0250b80-22a8-11eb-8190-56ba133a83de.png)
![fixed_label_2](https://user-images.githubusercontent.com/23359514/98547093-b0bda200-22a8-11eb-98f3-871797a8f8ee.png)

**Comment by christophine** [comment]
Noted, thank you, going to perform a git pull now and send an update. Regards.

**Comment by christophine** [comment]
Dear Joseph,

I have performed another git pull and everything seems fine but the land measurer is suggesting for the distances of the plots to appear inside the diagram figure rather than outside to avoid overlapping with the coordinates. See attached images below

![Coordinates](https://user-images.githubusercontent.com/52163423/98553755-9edbff00-22a8-11eb-9409-db5a1772a01b.PNG)
![Coordinates2PNG](https://user-images.githubusercontent.com/52163423/98553769-a26f8600-22a8-11eb-9ac1-7ea375260905.PNG)

**Comment by christophine** [comment]
Dear Joseph,

Are you available for a teams meeting tomorrow so that we can do the lodgment together, with emphasis on uploading the shapefiles because we are in-countering blank plots. Should you be available tomorrow, kindly let me know so that I can send out an invitation.

Regards,
Christophine

**Comment by jkariukidev** [comment]
> 
> 
> Dear Joseph,
> 
> I have performed another git pull and everything seems fine but the land measurer is suggesting for the distances of the plots to appear inside the diagram figure rather than outside to avoid overlapping with the coordinates. See attached images below
> 
> ![Coordinates](https://user-images.githubusercontent.com/52163423/98553755-9edbff00-22a8-11eb-9409-db5a1772a01b.PNG)
> ![Coordinates2PNG](https://user-images.githubusercontent.com/52163423/98553769-a26f8600-22a8-11eb-9ac1-7ea375260905.PNG)

Looking into that. Once it is fixed we will push the update.

**Comment by jkariukidev** [comment]
@christophine could you check it out now the latest updates have the measurements appearing inside the plot as shown here 
![image](https://user-images.githubusercontent.com/23359514/99021827-90286d00-2572-11eb-8145-847b1cf591a2.png)

**Comment by christophine** [comment]
Hi Joseph I will do that once I go to the Land Rights Office today.

**Comment by jkariukidev** [comment]
> 
> 
> Hi Joseph I will do that once I go to the Land Rights Office today.

Kindly confirm that the pending issues have been fixed on the plot numbers in the first map and that the line measurements are centered.

**Comment by christophine** [comment]
Dear Joseph, Just a confirmation the plot numbers and line measurements have been fixed. Thank you very much for you assistance.

**Comment by jkariukidev** [comment]
Ok. Great. Closing this issue.
