### ISSUE TITLE
Still not able to upload bigger files

### ISSUE THREAD

**Issue by christophine** [cb-flts/stdm#7]
We have changed the settings on the alfresco server but unable to upload bigger files. Even after restarting the service.  Bellow you can find the content of the server.xml file
Please look at line 68 and line 93 looks like a duplicate configuration.

<?xml version='1.0' encoding='utf-8'?>

<Server port="8005" shutdown="SHUTDOWN">
  
  
  <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
  
  
  <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
  

  
  <GlobalNamingResources>
    
    <Resource name="UserDatabase" auth="Container"
              type="org.apache.catalina.UserDatabase"
              description="User database that can be updated and saved"
              factory="org.apache.catalina.users.MemoryUserDatabaseFactory"
              pathname="conf/tomcat-users.xml" />
  </GlobalNamingResources>

  
  <Service name="Catalina">

    
    

    
    <Connector port="8080" URIEncoding="UTF-8" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443" maxHttpHeaderSize="102400000" 
			   maxPostSize="102400000" />
    
    
    
    

    
    <Connector port="8009" URIEncoding="UTF-8" protocol="AJP/1.3" redirectPort="8443" />

    <Connector port="8443" URIEncoding="UTF-8" protocol="org.apache.coyote.http11.Http11Protocol" SSLEnabled="true"
               maxThreads="150" scheme="https" keystoreFile="C:\alfresco/alf_data/keystore/ssl.keystore" keystorePass="kT9X6oe68t" keystoreType="JCEKS"
 secure="true" connectionTimeout="240000" truststoreFile="C:\alfresco/alf_data/keystore/ssl.truststore" truststorePass="kT9X6oe68t" truststoreType="JCEKS"
               clientAuth="want" sslProtocol="TLS" allowUnsafeLegacyRenegotiation="true" maxHttpHeaderSize="32768" maxSavePostSize="-1" />  

    

    
    <Engine name="Catalina" defaultHost="localhost">

      
      

      
      <Realm className="org.apache.catalina.realm.LockOutRealm">
        
        <Realm className="org.apache.catalina.realm.UserDatabaseRealm"
               resourceName="UserDatabase"/>
      </Realm>

      <Host name="localhost"  appBase="webapps"
            unpackWARs="true" autoDeploy="true">

        
        

        
        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="localhost_access_log" suffix=".txt"
               pattern="%h %l %u %t &quot;%r&quot; %s %b" />

      </Host>
    </Engine>
  </Service>
</Server>

**Comment by christophine** [comment]
When trying the upload bigger files this is the error I get.

![image](https://user-images.githubusercontent.com/52163423/62872388-a7e4c600-bd1d-11e9-8041-197f5246328e.png)

**Comment by gkahiu** [comment]
This is strange, let me look into it, will revert.

**Comment by christophine** [comment]
Ok thank you

**Comment by jkariukidev** [comment]
With [Alfresco 6.2]https://docs.alfresco.com/community/concepts/install-community-intro.html) uploading of large files has no issues. Check the test script used to test this in Windows 10 [here](https://gist.github.com/jkariukidev/8c86a8a361d5fa68df36df71d556e9ea).

**Comment by jkariukidev** [comment]
Sample file of 88MB can be uploaded to the repository.

![image](https://user-images.githubusercontent.com/23359514/108043043-a5b9a100-7051-11eb-973c-efd9be39be20.png)

Uploaded successfully.

![image](https://user-images.githubusercontent.com/23359514/108043192-de597a80-7051-11eb-82ce-e0ddcda45a39.png)
